const wordData =
{
  "Locations": [
    "School", "Library", "Mall", "Beach", "Airport", "Movie Theater", "Stadium", "Park", "Zoo", "Museum",
    "Restaurant", "Cafe", "Gym", "Hospital", "Police Station", "Fire Station", "Supermarket", "Gas Station", "Subway Station", "Train Station",
    "Bus Stop", "Amusement Park", "Water Park", "Aquarium", "Bowling Alley", "Arcade", "Skate Park", "Camping Site", "Lake", "River",
    "Mountain", "Desert", "Forest", "Island", "Bridge", "Tunnel", "Highway", "Farm", "Barn", "Castle",
    "Hotel", "Resort", "Concert Hall", "Theater Stage", "Classroom", "Auditorium", "Courthouse", "City Hall", "Bank", "Post Office",
    "Salon", "Barbershop", "Bakery", "Butcher Shop", "Pharmacy", "Tech Store", "Bookstore", "Clothing Store", "Shoe Store", "Toy Store",
    "Basketball Court", "Soccer Field", "Baseball Field", "Tennis Court", "Swimming Pool", "Ice Rink", "Locker Room", "Science Lab", "Computer Lab", "Art Room",
    "Principal's Office", "Rooftop", "Basement", "Attic", "Garage", "Kitchen", "Living Room", "Bedroom", "Bathroom", "Balcony",
    "Elevator", "Escalator", "Parking Lot", "Playground", "Volcano", "Cave", "Harbor", "Dock", "Lighthouse", "Observatory",
    "Planetarium", "Studio", "News Station", "Radio Station", "Factory", "Warehouse", "Greenhouse", "Courtyard", "Fountain", "Plaza",
    "Fox Den", "Wannan Gym"
  ],
  "Objects": [
    "Phone", "Laptop", "Tablet", "Headphones", "Backpack", "Notebook", "Pencil", "Pen", "Marker", "Highlighter",
    "Water Bottle", "Charger", "Keyboard", "Mouse", "Controller", "Television", "Remote", "Camera", "Tripod", "Microphone",
    "Speaker", "Watch", "Clock", "Sunglasses", "Wallet", "Keys", "Umbrella", "Jacket", "Sneakers", "Hat",
    "Helmet", "Skateboard", "Bicycle", "Scooter", "Car", "Bus", "Drone", "Flashlight", "Compass", "Map",
    "Trophy", "Medal", "Whistle", "Backboard", "Basketball", "Soccer Ball", "Baseball Bat", "Glove", "Tennis Racket", "Football",
    "Frisbee", "Yo-yo", "Puzzle", "Board Game", "Playing Cards", "Dice", "Rubik's Cube", "Action Figure", "Doll", "Stuffed Animal",
    "Toothbrush", "Hairbrush", "Mirror", "Soap", "Shampoo", "Towel", "Blanket", "Pillow", "Lamp", "Chair",
    "Desk", "Couch", "Table", "Refrigerator", "Microwave", "Oven", "Blender", "Toaster", "Plate", "Cup",
    "Fork", "Spoon", "Knife", "Scissors", "Tape", "Glue", "Stapler", "Calculator", "Ruler", "Paintbrush",
    "Easel", "Palette", "Battery", "Extension Cord", "Fan", "Heater", "Backpack Zipper", "Doorbell", "Alarm Clock"
  ],
  "Foods": [
    "Pizza", "Burger", "Hot Dog", "Tacos", "Burrito", "Sandwich", "Fries", "Nachos", "Pasta", "Spaghetti",
    "Mac and Cheese", "Ramen", "Fried Rice", "Sushi", "Dumplings", "Chicken Nuggets", "Grilled Cheese", "Pancakes", "Waffles", "French Toast",
    "Cereal", "Oatmeal", "Bagel", "Donut", "Muffin", "Croissant", "Cupcake", "Brownie", "Cookie", "Ice Cream",
    "Milkshake", "Smoothie", "Apple", "Banana", "Orange", "Grapes", "Strawberries", "Watermelon", "Pineapple", "Mango",
    "Carrot", "Broccoli", "Corn", "Mashed Potatoes", "Salad", "Soup", "Chili", "Steak", "Chicken Wings", "BBQ Ribs",
    "Popcorn", "Pretzels", "Chips", "Guacamole", "Salsa", "Cheese", "Yogurt", "Granola Bar", "Peanut Butter", "Jelly",
    "Eggs", "Bacon", "Sausage", "Quesadilla", "Fajitas", "Lasagna", "Meatballs", "Shrimp", "Fish Sticks", "Clam Chowder",
    "Chocolate", "Candy", "Lollipop", "Marshmallow", "Gummy Bears", "Jello", "Pie", "Cheesecake",
    "Ketchup", "Mustard", "Mayonnaise", "Honey", "Maple Syrup", "Pickles", "Avocado Toast", "Cinnamon Roll", "Onion Rings", "Sliders",
    "Fried Chicken", "Tater Tots", "Mozzarella Sticks", "Sourdough Bread", "Turkey Sandwich", "Caesar Salad", "Rice Bowl", "Protein Bar", "Acai Bowl", "Frozen Yogurt"
  ],
  "Sports": [
    "Basketball", "Soccer", "Baseball", "Football", "Tennis", "Volleyball", "Hockey", "Golf", "Swimming", "Track",
    "Cross Country", "Wrestling", "Boxing", "Martial Arts", "Karate", "Taekwondo", "Judo", "Skateboarding", "Surfing", "Snowboarding",
    "Skiing", "Biking", "BMX", "Rock Climbing", "Gymnastics", "Cheerleading", "Dance", "Rowing", "Sailing", "Archery",
    "Fencing", "Ping Pong", "Badminton", "Lacrosse", "Softball",
    "Dodgeball", "Pickleball", "Weightlifting", "Triathlon", "Marathon", "Long Jump", "Pole Vault",
    "Shot Put", "Discus", "Shotgun Shooting", "Esports", "Bowling", "Formula 1", "Figure Skating",
    "Ice Skating", "Table Tennis",
  ],
  "Movies/TV": [
    "Stranger Things", "Wednesday", "Outer Banks", "The Mandalorian", "Spider-Man No Way Home",
    "Avengers Endgame", "Black Panther", "Guardians of the Galaxy", "The Batman", "Joker",
    "Frozen", "Frozen II", "Moana", "Encanto", "Inside Out",
    "Toy Story", "Cars", "Finding Nemo", "The Incredibles", "Coco",
    "Turning Red", "Lightyear", "Zootopia",
    "The Hunger Games", "Harry Potter", "Percy Jackson",
    "Jurassic World", "Minions", "Despicable Me", "Shrek",
    "The Barbie Movie", "Wonka", "The Little Mermaid",
    "Aladdin", "Beauty and the Beast", "High School Musical", "The Greatest Showman",
    "Mean Girls", "Legally Blonde",
    "The Office", "Friends", "Brooklyn Nine-Nine", "The Simpsons", "Family Guy",
    "Gravity Falls", "Adventure Time", "Steven Universe", "Teen Titans", "Avatar The Last Airbender",
    "Cobra Kai", "The Flash", "Supergirl", "Arrow", "Smallville",
    "Squid Game",
    "Arcane", "One Piece",
    "Naruto", "Demon Slayer", "My Hero Academia", "Attack on Titan", "Dragon Ball Super",
    "Bluey", "iCarly", "Victorious", "Drake and Josh", "Hannah Montana",
    "Fuller House", "Young Sheldon", "Modern Family", "Glee", "Euphoria",
    "The Last of Us", "Wednesday Addams", "Five Nights at Freddy's", "The Conjuring", "A Quiet Place"
  ],
  "Music": [ "Sabrina Carpenter", "Ice Spice", "Billie Eilish", "Olivia Rodrigo", "Addison Rae", "Tate McRae",
        "Doja Cat", "Taylor Swift", "Drake", "The Weeknd", "Ariana Grande", "Charli XCX",
        "Lana Del Rey", "Benson Boone", "Tyler, The Creator",
        "Playboi Carti", "Future", "Yeat", 
        "Madison Beer", "Bruno Mars", "Ed Sheeran", "Justin Bieber",
        "Miley Cyrus", "Noah Kahan",
        "Kendrick Lamar", "Lil Nas X",
        "Morgan Wallen", "Baby Keem", "GloRilla", "Yuno Miles", "Bad Bunny"],
    "People": [
        "Timothée Chalamet",
        "Tom Holland",
        "Jacob Elordi",
        "Ryan Reynolds",
        "Millie Bobby Brown",
        "Kylie Jenner",
        "Kim Kardashian",
        "MrBeast",
        "Logan Paul",
        "LeBron James",
        "Stephen Curry",
        "Patrick Mahomes",
        "Drake Maye",
        "The Rock",
        "Ms. K",
        "Kayali",
        "Mormino",
        "Coach Square",
        "Mr. Gross",
        "Dr. Speece",
        "Mamadou",
        "Debnam",
        "there is no word just say random stuff"
    ]
}