const questionList = ["Held hands romantically?",
"Cheated on someone?",
"Kicked a roommate out to commit a sexual act?",
"Had severe memory loss due to alcohol?",
"Used a drug stronger than marijuana?",
"Been put on disciplinary probation or suspended?",
"Gone streaking?",
"Seen a stripper?",
"Had the police called on you?",
"Run from the police?",
"Had the police question you?",
"Had the police handcuff you?",
"Been arrested?",
"Been convicted of a crime?",
"Committed an act of vandalism?",
"Traveled 20 or more miles to get with someone?",
"Gotten with someone with an age gap of 3 or more years?",
"Committed an act of incest?",
"Engaged in bestiality?",
"Lied about something important to someoone playing right now?",
"Had more than 15hrs of screen time in one day?",
"Been naked in a hot tub with several other dudes?",
"Ego lifted at the gym to impress someone?",
"Been caught faking sobriety?",
"Been caught sneaking out?",
"Damaged the car while parking?",
"Damaged someone else's car while parking?",
"Caused a car accident?",
"Cheated on a test and still got below 50%?",
"Stolen something from someone playing right now?",
"Faked interest in someone to get something out of them?",
"Spread a rumor about someone?",
"Spread a rumor about someone playing right now?",
"Broken something at a func?",
"Stolen something from a func?",
"Come to school sick and started an outbreak?"]