const questionList = ["Held hands romantically?",
"Cheated on someone?",
"Had severe memory loss due to alcohol?",
"Used a drug stronger than marijuana?",
"Been put on disciplinary probation or suspended?",
"Had the police called on you?",
"Run from the police?",
"Had the police question you?",
"Committed an act of vandalism?",
"Lied about something important to someone playing?",
"Had more than 15hrs of screen time in one day?",
"Been naked in a hot tub with several other dudes?",
"Ego lifted at the gym to impress someone?",
"Been caught trying to act sober?",
"Been caught sneaking out?",
"Damaged your car while parking?",
"Damaged someone else's car while parking?",
"Caused a car accident?",
"Received money from AIPAC?",
"Failed a permit test?",
"Driven double the speed limit?",
"Cheated on a test and still got below 50%?",
"Stolen something from someone playing right now?",
"Faked interest in someone to get something out of them?",
"Wanted someone taken?",
"Broken something at a func?",
"Stolen something from a func?",
"Come to school sick and caused an outbreak?",
"Drunk texted someone you used to talk to?",
"Made a fake social media account to stalk someone?",
"Stalked someone's snapscore?",
"Led someone on?",
"Gone to Wegman's 3+ times in the same day?",
"Agreed with one of Osewe's hot takes?",
"Eaten a family-sized meal alone?",
"Had a situationship last 3+ months?",
"Been mad at someone for something you knew was your fault?",
"Tried to be an influencer?",
"Only heard about recent news on tiktok/reels/etc?",
"Been awake for more than 48 hours straight?",
"Had 9+ shots in one night?",
"(Recently) way overthought something you said?",
"(Recently) leaked something you shouldn't have?",
"(Recently) sent a text with the pleading eye emoji?",
"Ragebaited Vinnie?",
"Been ragebaited by Vinnie?",
"Lost over $100 from gambling in under two weeks?",
"Enlisted in the army as Langston Hill?",
"Bought something from Temu?",
"Pick gay son?",
"Broken a piece of senior center furniture?",
"Been on the receiving end of one-sided beef?",
"Been gaslit by someone about something important?",
"Added 20+ people from quick add in one day?",
"Faked an injury to get out of practice/a game/etc?"]