const questionList = ["Held hands romantically?",
"Cheated on someone?",
"Had severe memory loss due to alcohol?",
"Used a drug stronger than marijuana?",
"Been put on disciplinary probation or suspended?",
"Had the police called on you?",
"Run from the police?",
"Had the police question you?",
"Committed an act of vandalism?",
"Lied about something important to someoone playing right now?",
"Had more than 15hrs of screen time in one day?",
"Been naked in a hot tub with several other dudes?",
"Ego lifted at the gym to impress someone?",
"Been caught trying to act sober?",
"Been caught sneaking out?",
"Damaged the car while parking?",
"Damaged someone else's car while parking?",
"Caused a car accident?",
"Failed a permit test?",
"Cheated on a test and still got below 50%?",
"Stolen something from someone playing right now?",
"Faked interest in someone to get something out of them?",
"Broken something at a func?",
"Stolen something from a func?",
"Come to school sick and caused an outbreak?",
"Drunk texted someone you used to talk to?",
"Repeatedly stalked the same person's socials?",
"Led someone on?",
"Gone to Wegman's 3+ times in the same day?",
"Been caught GPTing an essay?",
"Rejected someone for a made up reason?"]